version: '3'
services:

  minio:
    image: 'minio/minio'
    ports:
      - '9000:9000'
      - '9001:9001'    
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=bklite-minio-password
    command: server --console-address :9001 /data
    networks:
      - traefik    
    volumes:
      - minio:/data

networks:
  traefik:
    external: true

volumes:
  minio: