version: '3'
services:

  postgres:
    image: ccr.ccs.tencentyun.com/bklite/postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./schema:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - traefik      
    restart: always


networks:
  traefik:
    external: true

volumes:
  postgres: