networks:
  prod:

services:
  cmdb:
    image: ${DOCKER_IMAGE_CMDB}
    restart: always
    environment:
      DEBUG: 0
      INSTALL_APPS: cmdb
      SECRET_KEY: ${SECRET_KEY}
      DB_ENGINE: postgresql
      DB_USER: ${POSTGRES_USERNAME}
      DB_HOST: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: "5432"
      NATS_SERVERS: nats://${NATS_ADMIN_USERNAME}:${NATS_ADMIN_PASSWORD}@nats:4222
      NATS_NAMESPACE: bk-lite
      CLIENT_ID: cmdb
      DB_NAME: cmdb
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: ${NEO4J_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      VICTORIAMETRICS_HOST: http://victoria-metrics:8428
      ENABLE_CELERY: True
      BROKER_URL: redis://:${REDIS_PASSWORD}@redis:6379/11
      CELERY_BROKER_URL: redis://:${REDIS_PASSWORD}@redis:6379/11
      CELERY_RESULT_BACKEND: redis://:${REDIS_PASSWORD}@redis:6379/11
      REDIS_CACHE_URL: redis://:${REDIS_PASSWORD}@redis:6379/11
      CELERY_WORKER_CONCURRENCY: 1
    networks:
      - prod
    depends_on:
      system-manager:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-s", "-o", "/dev/null", "-w", "'%{http_code}'", "http://cmdb:8000/healthcheck"]
  
  cmdb-web:
    image: ${DOCKER_IMAGE_CMDB_WEB}
    restart: always
    environment:
      NEXTAUTH_URL: http://${HOST_IP}:${TRAEFIK_CMDB_PORT}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAPI_URL: http://cmdb:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cmdb-web.rule=Host(`${HOST_IP}`)"
      - "traefik.http.routers.cmdb-web.entrypoints=cmdb-web"
      - "traefik.http.services.cmdb-web.loadbalancer.server.port=3000"
    networks:
      - prod
    depends_on:
      - cmdb
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://cmdb-web:3000/healthcheck').then(res => res.status === 200)"]
      start_period: 5s
