networks:
  prod:

services:
  server:
    image: ${DOCKER_IMAGE_SERVER}
    environment:
      - DEBUG=True
      - SECRET_KEY=${SECRET_KEY}
      - JWT_ALGORITHM=HS256
      - NATS_SERVERS=nats://${NATS_ADMIN_USERNAME}:${NATS_ADMIN_PASSWORD}@nats:4222
      - NATS_NAMESPACE=bklite
      - DB_ENGINE=postgresql
      - DB_NAME=bklite
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=5432
      - ADMIN_PASSWORD=password
      - ENABLE_CELERY=true
      - CELERY_WORKER_CONCURRENCY=1
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/3
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/3
      - DEFAULT_ZONE_VAR_NATS_SERVERS=${HOST_IP}:4222
      - DEFAULT_ZONE_VAR_NATS_PASSWORD=${NATS_ADMIN_PASSWORD}
      - DEFAULT_ZONE_VAR_NATS_USERNAME=${NATS_ADMIN_USERNAME}
      - DEFAULT_ZONE_VAR_STARGAZER_URL=http://stargazer:8083
      - DEFAULT_ZONE_VAR_NODE_SERVER_URL=http://${HOST_IP}:${TRAEFIK_WEB_PORT}
      - SIDECAR_INIT_TOKEN=${SIDECAR_INIT_TOKEN}
      - VICTORIAMETRICS_HOST=http://victoria-metrics:8428
      - TOP_GROUP=Default
      - DEFAULT_GROUP_NAME=Guest
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - MINIO_ENDPOINT=minio:9000
      - MINIO_USE_HTTPS=0
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - CONVERSATION_MQ_HOST=rabbitmq
      - CONVERSATION_MQ_PORT=5672
      - CONVERSATION_MQ_USER=${RABBITMQ_DEFAULT_USER}
      - CONVERSATION_MQ_PASSWORD=${RABBITMQ_DEFAULT_PASSWORD}
      - MUNCHKIN_BASE_URL=http://${HOST_IP}:${TRAEFIK_WEB_PORT}/opspilot
      - METIS_SERVER_URL=http://metis:18083
      - PILOT_RUNTIME=docker
      - INSTALL_APPS=${INSTALL_APPS}
    healthcheck:
      test: ["CMD", "curl", "-s", "-o", "/dev/null", "-w", "'%{http_code}'", "http://127.0.0.1:8000/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - prod
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sidecar.rule=Host(`${HOST_IP}`) && PathPrefix(`/node_mgmt`) || PathPrefix(`/opspilot/bot_mgmt`)"
      - "traefik.http.routers.sidecar.entrypoints=web"
      - "traefik.http.services.sidecar.loadbalancer.server.port=8000"