version: '3.8'

services:
  docs-site:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: bk-lite-docs
    restart: unless-stopped
    
  # 开发模式服务
  docs-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    container_name: bk-lite-docs-dev
    environment:
      - NODE_ENV=development
    command: pnpm dev
    profiles:
      - dev
