apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pilot-{{bot_id}}
spec:  
  entryPoints:
    {% if enable_ssl %}
    - websecure
    {% else %}
    - web
    {% endif %}
  routes:
    - match: Host(`{{bot_domain}}`) && PathPrefix(`/pilot-{{bot_id}}`)
      kind: Rule
      services:
        - name: pilot-{{ bot_id }}-service
          port: 5005
      middlewares:
        - name: strip-{{bot_id}}-prefix