apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobe-chat-{{bot_id}}
spec:
  replicas: {{replicas}}
  selector:
    matchLabels:
      app: lobe-chat-{{bot_id}}
  template:
    metadata:
      labels:
        app: lobe-chat-{{bot_id}}
    spec:
      containers:
        - name: lobe-chat-{{bot_id}}
          image: bklite/lobe-chat
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: OPENAI_PROXY_URL
              value: "{{base_url}}"
            - name: OPENAI_API_KEY
              value: "{{api_key}}"
            - name: BK_LITE_APP_ID
              value: "{{bot_id}}"
            - name: OPENAI_MODEL_LIST
              value: "{{model_list}}"
            - name: NEXT_PUBLIC_ENABLE_NEXT_AUTH
              value: "1"
            - name: NEXT_AUTH_SECRET
              value: "{{api_key}}"
            - name: NEXT_AUTH_SSO_PROVIDERS
              value: "bklite"
            - name: AUTH_BKLITE_API_URL
              value: "{{login_url}}"
          ports:
            - containerPort: 3210

