version: '3'
services:
  
  neo4j:
    image: neo4j
    container_name: neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
      - "7473:7473"
    environment:
      - NEO4J_AUTH=neo4j/neo4j_password
    networks:
      - traefik      
    volumes:
      - neo4j:/data

networks:
  traefik:
    external: true

volumes:
  neo4j: