version: '3'
services:
  elasticsearch:
    image: 'ccr.ccs.tencentyun.com/bklite/elasticsearch'
    ports:
      - '9200:9200'
    restart: always
    environment:
       discovery.type: "single-node"
       xpack.security.enabled: "true"
       ELASTIC_PASSWORD: "password"
       TZ: "UTC"
       ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - traefik       
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

networks:
  traefik:
    external: true

volumes:
  elasticsearch: