version: '3'
services:
  opspilot-web:
    image: bklite/ops-pilot-web
    container_name: opspilot-web
    environment:
      NEXTAUTH_URL: http://127.0.0.1:42005
      NEXTAUTH_SECRET: aebeibuaV4Qu
      NEXTAPI_URL: http://opspilot:8000
    restart: always
    ports:
      - 42005:3000
    networks:
      - traefik

  opspilot:
    image: bklite/ops-pilot
    container_name: ops-pilot
    restart: always
    ports:
      - 32005:8000
    environment:
      DEBUG: 'True'
      SECRET_KEY: f8e2b4d1-9c5a-4e67-b3f2-8a1d6c9e4b7f
      DB_ENGINE: postgresql
      DB_NAME: opspilot
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
      MINIO_ENDPOINT: minio:9000
      MINIO_USE_HTTPS: 0
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: bklite-minio-password
      CELERY_RESULT_BACKEND: db+postgresql://postgres:password@postgres/opspilot
      CELERY_BROKER_URL: amqp://admin:password@rabbitmq:5672//
      CONVERSATION_MQ_HOST: rabbitmq
      CONVERSATION_MQ_PORT: 5672
      CONVERSATION_MQ_USER: admin
      CONVERSATION_MQ_PASSWORD: password
      KUBE_NAMESPACE: bklite
      MUNCHKIN_BASE_URL: http://opspilot:8000
      NATS_SERVERS: nats://admin:nats_password@nats:4222
      NATS_NAMESPACE: bklite
      CLIENT_ID: opspilot
      ADMIN_PASSWORD: bklite
      METIS_SERVER_URL: http://10.8.0.14:8080
      INSTALL_APPS: opspilot
      PILOT_RUNTIME: docker

    networks:
      - traefik      

networks:
  traefik:
    external: true

volumes:
  vlog-data: