version: '3'
services:
  victorialogs:
    image: victoriametrics/victoria-logs:v1.17.0-victorialogs
    restart: always
    ports:
      - 9428:9428
    networks:
      - traefik      
    volumes:
      - vlog-data:/vlogs
    command:
      - -storageDataPath=/vlogs
      - -loggerFormat=json

networks:
  traefik:
    external: true

volumes:
  vlog-data: