version: '3'
services:
  system-manager-web:
    image: bklite/system-manager-web
    container_name: system-manager-web
    environment:
      NEXTAUTH_URL: http://127.0.0.1:42000
      NEXTAUTH_SECRET: aebeibuaV4Qu
      NEXTAPI_URL: http://system-manager:8000
    restart: always
    ports:
      - 42000:3000
    networks:
      - traefik

  system-manager:
    image: bklite/system-manager
    container_name: system-manager
    restart: always
    ports:
      - 32000:8000
    environment:
      DEBUG: 'True'
      SECRET_KEY: "f8e2b4d1-9c5a-4e67-b3f2-8a1d6c9e4b7f"
      JWT_ALGORITHM: 'HS256'
      INSTALL_APPS: system_mgmt
      DB_ENGINE: postgresql
      DB_NAME: system_mgmt
      DB_USER: postgres
      DB_HOST: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
      
      NATS_SERVERS: nats://admin:nats_password@nats:4222
      NATS_NAMESPACE: bklite
      CLIENT_ID: system-manager

      IS_USE_CELERY: 'false'
      DEFAULT_GROUP_NAME: Guest
      TOP_GROUP: Default

    networks:
      - traefik      

networks:
  traefik:
    external: true
