version: '3'
services:
  nats:
    image: ccr.ccs.tencentyun.com/bklite/nats:2.10.25 
    container_name: nats
    volumes:
      - nats:/nats
      - ./conf/nats.conf:/etc/nats/nats.conf
      # - ./conf/certs:/etc/nats/certs
    ports:
      - "4222:4222"
    command:
      - -c
      - /etc/nats/nats.conf
      - --user
      - admin
      - --pass
      - nats_password
    networks:
      - traefik      
    restart: always


networks:
  traefik:
    external: true

volumes:
  nats: