version: '3.7'

services:
    mlflow:
      restart: always
      image: bklite/mlflow
      container_name: mlflow
      ports:
        - "15000:15000"
      environment:
        - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
        - AWS_ACCESS_KEY_ID=minio
        - AWS_SECRET_ACCESS_KEY=bklite-minio-password
        - MLFLOW_S3_IGNORE_TLS=true
        - AWS_DEFAULT_REGION=us-east-1
      # command: mlflow server --backend-store-uri postgresql://postgres:password@postgres:5432/mlflow --default-artifact-root s3://mlflow/ --serve-artifacts --host 0.0.0.0 --port 15000
      command: mlflow server --host 0.0.0.0 --port 15000
      networks:
        - traefik

networks:
    traefik:
      external: true