version: '3'
services:
  victoria-metrics:
    image: ccr.ccs.tencentyun.com/bklite/victoria-metrics:v1.106.1
    container_name: victoria-metrics
    volumes:
      - victoria-metrics:/victoria-metrics-data
    ports:
      - "8428:8428"
    command:
      - --storageDataPath=/victoria-metrics-data
      - --httpListenAddr=0.0.0.0:8428
      - --retentionPeriod=168h
      - -maxLabelsPerTimeseries=300
    networks:
      - traefik      
    restart: always

networks:
  traefik:
    external: true

volumes:
  victoria-metrics: