version: '3'
services:

  fusion-collector:
    image: bklite/fusion-collector
    container_name: fusion-collector
    environment:
      - SERVER_URL=http://node-manager:8000/node_mgmt/open_api/node
      - SERVER_API_TOKEN=iuCQqhH9otu_H3G4YOTvTnndUOqu5K4XdRz1Yyh39mUueyJ1c2VybmFtZSI6ICJhZG1pbiJ9
      - SIDECAR_ZONE=default
      - SIDECAR_GROUP=1
      - SIDECAR_NODEID=1
      - SIDECAR_NODENAME=fusion-collector
    networks:
      - traefik      
    restart: always


networks:
  traefik:
    external: true
