version: '3'
services:
 
  vector:
    image: ccr.ccs.tencentyun.com/bklite/vector:0.34.1-debian
    container_name: vector
    ports:
      - 8686:8686
    networks:
      - traefik      
    volumes:
      - ./conf/vector.yaml:/etc/vector/vector.yaml:ro
    restart: always

networks:
  traefik:
    external: true