version: '3'
services:

  telegraf:
    image: bklite/telegraf
    container_name: telegraf
    environment:
      - METRIC_NATS_USERNAME=admin
      - METRIC_NATS_PASSWORD=5FE2MUTR7ZaLRVx7uAuObRnmBYxMG
      - METRIC_OUTPUT_URL=http://victoria-metrics:8428
      - METRIC_NATS_SERVERS=nats://nats:4222
    networks:
      - traefik      
    volumes:
      - ./conf/telegraf.conf:/apps/telegraf.conf
      # - ./conf/ca.pem:/etc/nats/ca.pem
      # - ./conf/client-cert.pem:/etc/nats/client-cert.pem
      # - ./conf/client-key.pem:/etc/nats/client-key.pem
    restart: always


networks:
  traefik:
    external: true
