version: '3'
services:

  redis:
    image: ccr.ccs.tencentyun.com/bklite/redis:5.0.14
    container_name: redis
    command: redis-server --requirepass password
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - traefik      
    restart: always


networks:
  traefik:
    external: true

volumes:
  redis: