version: '3'
services:
  node-manager-web:
    image: bklite/node-manager-web
    container_name: node-manager-web
    environment:
      NEXTAUTH_URL: http://127.0.0.1:42002
      NEXTAUTH_SECRET: aebeibuaV4Qu
      NEXTAPI_URL: http://node-manager:8000
    restart: always
    ports:
      - 42002:3000
    networks:
      - traefik

  node-manager:
    image: bklite/node-manager
    container_name: node-manager
    restart: always
    ports:
      - 32002:8000
    environment:
      - DEBUG=0
      - INSTALL_APPS=node_mgmt
      - SECRET_KEY=f8e2b4d1-9c5a-4e67-b3f2-8a1d6c9e4b7f
      - CLIENT_ID=node
      - SIDECAR_INPUT_MODE=nats
      - IS_USE_CELERY=True
      - CELERY_BROKER_URL=redis://:password@redis:6379/2
      - DB_PORT=5432
      - DB_NAME=node_mgmt
      - DEFAULT_ZONE_VAR_NATS_SERVERS=nats:4222
      - DEFAULT_ZONE_VAR_NATS_PASSWORD=nats_password
      - DEFAULT_ZONE_VAR_NATS_USERNAME=admin
      - DEFAULT_ZONE_VAR_STARGAZER_URL=http://stargazer:8083
      - DEFAULT_ZONE_VAR_NODE_SERVER_URL=http://node-manager:8000/
      - NATS_NAMESPACE=bklite
      - SIDECAR_INIT_TOKEN=sidecar_token
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_PASSWORD=password
      - DB_ENGINE=postgresql
      - NATS_SERVERS=nats://admin:nats_password@nats:4222

    networks:
      - traefik      

networks:
  traefik:
    external: true

volumes:
  vlog-data: